index.html

Per @iherman's wonderful recommendations, some changes and amendments to the audiobooks spec.

Editorial Changes

---

index.html

Adding the usage of `AudioObject` for items in the readingOrder. After reviewing the `AudioObject` in schema.org I think this is a grat type option for reading order items, it gives us all of the attributes we need.
***
<a href="https://pr-preview.s3.amazonaws.com/wareid/audiobooks/pull/4.html" title="Last updated on Jun 11, 2019, 3:33 PM UTC (acfd09e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/4/58932bb...wareid:acfd09e.html" title="Last updated on Jun 11, 2019, 3:33 PM UTC (acfd09e)">Diff</a>

Adding `AudioObject` and minor corrections

---

index.html
snapshot/index.html

I updated the snapshot also...not sure if that's how it's done or not. 😃 
`https://w3c.org/` throws a security warning...which is how I found these.
Cheers!
🎩
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/pull/21.html" title="Last updated on Sep 16, 2019, 2:40 AM UTC (1dc40bc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/21/93ed099...1dc40bc.html" title="Last updated on Sep 16, 2019, 2:40 AM UTC (1dc40bc)">Diff</a>

Fix various w3.org related typos

---

index.html

In addition to the changes in https://github.com/w3c/pub-manifest/pull/131, this PR removes section
2.2.1 and updates the third bullet in the toc requirements to reference the publication resources section.
Addresses #26.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/pull/29.html" title="Last updated on Oct 22, 2019, 7:10 PM UTC (a189d1f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/29/7870fdc...a189d1f.html" title="Last updated on Oct 22, 2019, 7:10 PM UTC (a189d1f)">Diff</a>

Remove references to "bounds"

---

index.html

Some minor shuffling of the preliminary stuff to match pub-manifest.
I took the one floating sentence in the intro and moved it to the abstract as the abstract was talking about the specification being a draft. Seemed like a good drop-in replacement, anyway.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/pull/38.html" title="Last updated on Nov 11, 2019, 10:35 PM UTC (c91b641)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/38/506dd2c...c91b641.html" title="Last updated on Nov 11, 2019, 10:35 PM UTC (c91b641)">Diff</a>

minor section shuffling

---

index.html

Here's a start on extending the manifest processing algorithms. It will need to be updated depending on how the various issues I've opened are resolved. (I promise no more now! :)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/pull/45.html" title="Last updated on Nov 12, 2019, 10:22 PM UTC (b75a560)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/45/506dd2c...b75a560.html" title="Last updated on Nov 12, 2019, 10:22 PM UTC (b75a560)">Diff</a>

extend manifest processing for audio rules

---

index.html

This PR addresses the following issues:
- #55 - adds a validity check on duration for resources, and removes the relation check for privacy policy and a11y report
- #51 - removes the duplicate global duration check
- #49 - removes links as a recommended property
- #48 - add back the publication type section with note that audiobook is assumed when not set
- #47 - updates reference to pub manifest data models
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/pull/56.html" title="Last updated on Nov 16, 2019, 8:46 PM UTC (5df2f13)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/56/d217921...5df2f13.html" title="Last updated on Nov 16, 2019, 8:46 PM UTC (5df2f13)">Diff</a>

Fixes to algorithm issues

---

index.html

Sorry, I just noticed a bug with the processing - checking/removing non-audio resources can result in an empty reading order, but the fatal error for an empty reading order currently precedes this step. It also isn't necessary to check if there is at least one audio resource before removing non-audio resources, since the fatal error ensures the reading order is non-empty.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/pull/59.html" title="Last updated on Nov 22, 2019, 3:30 PM UTC (fc857ca)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/59/31d87aa...fc857ca.html" title="Last updated on Nov 22, 2019, 3:30 PM UTC (fc857ca)">Diff</a>

check if reading order is empty after processing entries

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/marisademeglio/audiobooks/pull/60.html" title="Last updated on Nov 27, 2019, 3:08 AM UTC (4050331)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/60/03d7330...marisademeglio:4050331.html" title="Last updated on Nov 27, 2019, 3:08 AM UTC (4050331)">Diff</a>

Correct references to Synchronized Narration 

---

index.html

Two proposed changes:
- Added a section extending the generic ToC algorithm by specifying that the ToC should be located first in the PEP. This is the PR counterpart of https://github.com/w3c/audiobooks/issues/63 and is also based on https://github.com/w3c/pub-manifest/pull/183
- Added a processing point that the PEP (if present) must be part of unique resources. Otherwise, the TOC algorithm does not work. This is the PR counterpart of https://github.com/w3c/publ-tests/issues/7
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/pull/66.html" title="Last updated on Dec 19, 2019, 2:31 PM UTC (4cb6a23)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/66/ecaf2dc...4cb6a23.html" title="Last updated on Dec 19, 2019, 2:31 PM UTC (4cb6a23)">Diff</a>

Settling PEP and ToC handling 

---

index.html

This PR fixes #70 by moving the manifest requirements up a level to match pub manifest and adds "resource relations" so that cover isn't out of place in the list.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/pull/72.html" title="Last updated on Feb 6, 2020, 1:00 PM UTC (61ca542)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/72/c72b917...61ca542.html" title="Last updated on Feb 6, 2020, 1:00 PM UTC (61ca542)">Diff</a>

fix for cover relation

---

index.html

Alas! the W3C publication rules require US English spelling, so British is not o.k....
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/pull/74.html" title="Last updated on Feb 10, 2020, 2:38 PM UTC (64b87ec)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/74/e001d06...64b87ec.html" title="Last updated on Feb 10, 2020, 2:38 PM UTC (64b87ec)">Diff</a>

Changed 'behaviour' to 'behavior'

---

index.html

This PR fixes #71 in a slightly different way than mentioned. I noticed that we're issuing validation errors and removing duration properties here, but it's also checked globally as part of the general manifest processing of linked resources. While a bit harmless, it's unnecessarily duplicative and also not really in the scope of this particular check.
So aside from reordering the steps to ensure there is a valid total duration before computing the durations of each resource, I dropped the warning/removal parts so they're all issued from the same step later.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/pull/73.html" title="Last updated on Feb 11, 2020, 12:49 PM UTC (df15bca)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/73/c72b917...df15bca.h …

fix total duration check

---

index.html

Addressing the issue raised in #68
* corrected the time references
* edited the TOC example with media fragments
* added a note addressing not referencing the same audio file multiple times in the reading order
Feedback appreciated!
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/pull/69.html" title="Last updated on Feb 12, 2020, 1:00 PM UTC (648560b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/69/c72b917...648560b.html" title="Last updated on Feb 12, 2020, 1:00 PM UTC (648560b)">Diff</a>

Adjusting the text for Media fragments

---

index.html

Added an additional note about annotations per issue #76.
Lars will add more about deep linking for future revisions.
***
:boom: ###
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Mar 16, 2020, 3:23 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [HTML Diff Service](http://services.w3.org/htmldiff) - The HTML Diff Service is used to create HTML diffs of the spec changes suggested in a pull request.
:link: [Related URL](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fpr-preview.s3.amazonaws.com%2Fw3c%2Faudiobooks%2Fpull%2F77%2Fff9bc78.html&doc2=https%3A%2F%2Fpr-preview.s3.amazonaws.com%2Fw3c%2Faudiobooks%2Fpull%2F77.html) …

Adding to the media fragments section

---

index.html
schema/README.md
schema/audiobooks.schema.json

Adds a new primary driver file that expects the Audiobooks type, audiobooks conformsTo URL and requires title and readingOrder.
I haven't added all the component files, as it seems like a nuisance to maintain them in two places. I've instead noted in the readme they have to be downloaded. Always open to changing that, though.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/pull/81.html" title="Last updated on Jul 3, 2020, 3:00 PM UTC (9a79c7a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/81/9b2df26...9a79c7a.html" title="Last updated on Jul 3, 2020, 3:00 PM UTC (9a79c7a)">Diff</a>

add audiobook schema

---

index.html

Fixes #82 as follows:
- rewords the note at the top of the section to indicate that descriptive labels are in parentheses;
- adds property names and styling for all items in the list;
- puts descriptive labels in parentheses after for any names that aren't self-explanatory
- breaks out the five individual accessibility properties
- re-alphabetizes the list
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/pull/84.html" title="Last updated on Jul 3, 2020, 3:50 PM UTC (8beb799)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/84/9b2df26...8beb799.html" title="Last updated on Jul 3, 2020, 3:50 PM UTC (8beb799)">Diff</a>

add property names to the manifest requirements list

---

index.html
schema/README.md
schema/audiobooks.schema.json

As [resolved on the telecon today](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2020/2020-07-27-pwg), updating the URLs to w3c addresses to fix https://github.com/w3c/pub-manifest/issues/226.
Same as with the other PR, we'll need to make sure the redirects are up and running before merging.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/pull/85.html" title="Last updated on Jul 29, 2020, 10:20 PM UTC (114a5b6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/85/ba8af37...114a5b6.html" title="Last updated on Jul 29, 2020, 10:20 PM UTC (114a5b6)">Diff</a>

Update schema urls to w3c address

---

experiments/flatland.json
index.html

There was two leftover `wp-context` usage in the examples... Changed them to `pub-context`
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/pull/86.html" title="Last updated on Jul 28, 2020, 7:20 AM UTC (6546e7b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/86/ba8af37...6546e7b.html" title="Last updated on Jul 28, 2020, 7:20 AM UTC (6546e7b)">Diff</a>

Changed wp-context to pub-context

---

index.html

This PR fixes #87 by changing the first two paragraphs of the accessibility section to:
> The history of the audiobook is rooted in the world of accessibility. Both purely audio publications and publications that synchronize text and audio playback have long been used to assist users with alternative reading needs and preferences.
> 
> An approach for accessible synchronized media in publications is currently being done by the Synchronized Multimedia for Publications Community group. Refer to the work of that group for more information about creating such content and incorporating it into an Audiobook.
and removing the example.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/pull/88.html" title="Last updated on Aug 26, 2020, 4:57 PM UTC (5a05953)">Preview</a> | <a …

Update reference and remove example for synchronized narration

---

index.html

Fixes #61 by adding the prose suggested in https://github.com/w3c/audiobooks/issues/61#issuecomment-687312361
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/pull/90.html" title="Last updated on Sep 8, 2020, 12:20 PM UTC (42372ae)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/90/c8d01b5...42372ae.html" title="Last updated on Sep 8, 2020, 12:20 PM UTC (42372ae)">Diff</a>

clarify primary entry page requirement

---

index.html

Fixes #93 by removing the problematic step.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/pull/95.html" title="Last updated on Sep 12, 2020, 10:30 AM UTC (22e1c4b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/95/bc1bcd1...22e1c4b.html" title="Last updated on Sep 12, 2020, 10:30 AM UTC (22e1c4b)">Diff</a>

remove the processing step that checks for a table of contents

---

index.html

To better reflect the importance of the TOC in light of the change in PR #111 and issue #110, I am updating the language in the TOC section, and adding a note. This is to clarify that in the event of audio files containing more than one chapter/section, the TOC should be used to display that granularity.
Feel free to offer editorial advice, it is much needed.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/pull/114.html" title="Last updated on Feb 22, 2022, 3:14 PM UTC (3894abb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/114/ceb65ec...3894abb.html" title="Last updated on Feb 22, 2022, 3:14 PM UTC (3894abb)">Diff</a>

Updating TOC Section to reflect changes

---

index.html

I applied the style and structure necessary for the update of a Recommendation. This should only be applied to _normative_ changes.
The essential point is: the changes should _remain_ in the document, ie, both the old and new, suitably included in `<del>` and `<ins>` elements, and linking to the short description of the changes. The rest (adding buttons to show old or new) is done by a JS magic included by respec.
This should only happen with normative changes!
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/pull/113.html" title="Last updated on Feb 17, 2022, 2:44 PM UTC (22adf8d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/113/4f87254...22adf8d.html" title="Last updated on Feb 17, 2022, 2:44 PM UTC (22adf8d)">Diff</a>

Update the editorial style for normative changes
